name: test_on_push

on:
  push:
    branches:
      - main
  workflow_dispatch: # now i can also manually execute it

jobs:
  testJob1:
    runs-on: ubuntu-latest # github will make an environment for us
    steps:
      - name: check out # brings our project into the virtual environment
        uses: actions/checkout@v3 
  
      - name: setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet version: '8.0.x'

      - name: dependencies # this step installs dependencies
        run: dotnet restore

      - name: make a build # making a build of our project
        run: dotnet build

      - name: run tests # running the tests
        run: dotnet test --filter FullyQualifiedName!~SeleniumTest #exclude selenium because it doesn't work :)
          
      - name: Start the API
        run: |
          nohup dotnet run --project ./PersonalDataGenerator/PersonalDataGenerator.csproj --urls http://localhost:5268 &
        env:
          ASPNETCORE_URLS: http://localhost:5268
        continue-on-error: true  # Continue even if this step fails
          
      - name: Install Newman
        run: npm install -g newman
          
      - name: Run Postman tests with Newman
        run: |
          newman run PersonalDataGenerator.Tests/postman/PersonalDataGenerator.postman_collection.json \
            --env-var baseUrl="http://localhost:5268" \
            --reporters cli,junit    
          
          
          
          
          
  
        